on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  check-for-new:
    runs-on: ubuntu-latest

    steps:
      - name: Check if labelled as "new"
        run: |
          if [ "${{ contains(github.event.pull_request.labels.*.name, 'new') }}" = true ]; then
            echo "::error::This PR is still too new to merge"
            exit 1
          fi
