on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  label-as-new:
    runs-on: ubuntu-latest

    steps:
      - name: Label as "new"
        uses: andymckay/labeler@1.0.3
        with:
          add-labels: "new"
          ignore-if-assigned: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}
