services:
  test:
    build:
      context: .
      target: test
      args:
        RAILS_ENV: "test"
    command: bundle exec rake
    ports:
      - "3000:3000"
    depends_on:
      - test-db
    env_file:
       - .env.test
    environment:
      DATABASE_URL: postgres://postgres:password@test-db:5432/app-test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      AUTOMATICALLY_FIX_LINTING: "true"
    volumes:
      - .:/srv/app
    tty: true
    stdin_open: true
    networks:
      - test

  test-db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - test

networks:
  test:
volumes:
  db-data:
