#!/bin/sh

# Launch a console for the application. Optionally pass in an environment name
# to connect to a console for that environment.

set -e

# Enable the running of this script from any subdirectory without moving to root
cd "$(dirname "$0")/../.."

ENVIRONMENT=$1

if [ -n "$ENVIRONMENT" ]; then
  case "$ENVIRONMENT" in
    *)
      echo "Unknown environment '$ENVIRONMENT'"
      exit 1
      ;;
  esac
else
  echo "==> Updating..."
  script/no-docker/update

  echo "==> Starting a local Rails console..."
  bundle exec rails console
fi
