#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

echo "==> Updating..."
script/no-docker/update

echo "==> Starting the development server..."
bundle exec rails server
