#!/bin/sh

# Update application to run for its current checkout.

set -e

echo "==> Bootstrapping..."
script/no-docker/bootstrap

echo "==> Running database migrations..."
bundle exec rails db:migrate

echo "==> Running test database migrations..."
RAILS_ENV="test" bundle exec rails db:migrate
