#!/bin/sh

# Resolve all dependencies that the application requires to run.

set -e

# Enable the running of this script from any subdirectory without moving to root
cd "$(dirname "$0")/../.."

echo "==> Building web Docker image..."
docker-compose build web

echo "==> Building test Docker image..."
docker-compose -f docker-compose.test.yml build test
