#!/bin/sh

# Update application to run for its current checkout.

set -e

# Enable the running of this script from any subdirectory without moving to root
cd "$(dirname "$0")/../.."

echo "==> Bootstrapping..."
script/docker/bootstrap
