#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

# Enable the running of this script from any subdirectory without moving to root
cd "$(dirname "$0")/.."

. script/all/process-script-args

if [ "$DOCKER" -eq 1 ]; then
  echo "==> Running with Docker..."
  script/docker/bootstrap "$@"
else
  echo "==> Running natively (no docker)..."
  script/no-docker/bootstrap "$@"
fi
