#!/bin/sh

# script/console: Launch a console for the application. Optionally pass in an
#                 environment name to connect to a console for that environment.

set -e

docker-compose run --rm web bundle exec rails console
