#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

docker-compose up --detach
# TODO: Repace 'rails-template' with application name
docker attach rails-template_1
