#!/bin/sh

# Run the test suite for the application. Optionally pass in a path to an
# individual test file to run a single test.

TEST_FILES=$1

if [ -n "$TEST_FILES" ]; then
  echo "==> Running the tests matching '$TEST_FILES'..."
  bundle exec rspec "$TEST_FILES"
else
  if [ -n "$AUTOMATICALLY_FIX_LINTING" ]; then
    echo "==> Formatting files..."
    yarn run lint:format:fix
  else
    echo "==> Checking formatting..."
    yarn run lint:format
  fi

  echo "==> Running ShellCheck..."
  find script -type f -exec shellcheck {} +

  if [ -n "$AUTOMATICALLY_FIX_LINTING" ]; then
    echo "==> Linting Ruby in fix mode..."
    bundle exec standardrb --fix
  else
    echo "==> Linting Ruby..."
    bundle exec standardrb
  fi

  if [ -n "$AUTOMATICALLY_FIX_LINTING" ]; then
    echo "==> Linting JS in fix mode..."
    yarn run lint:js:fix
  else
    echo "==> Linting JS..."
    yarn run lint:js
  fi

  echo "==> Running the tests..."
  bundle exec rspec

  echo "==> Running Brakeman..."
  bundle exec brakeman -o /dev/stdout
fi
