#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally. Use variables to control how you want to provision
#                your local environment.
#                Eg. `DOCKER=true script/console`
#                Or, add this as a global variable to your shell so it's set
#                automatically.

set -e

# Enable the running of this script from any subdirectory without moving to root
cd "$(dirname "$0")/.."

echo "==> Loading command line options…"
DOCKER=${PREFER_DOCKER_FOR_DXW_RAILS:-0}
for arg in "$@"
do
  case $arg in
    --docker)
      DOCKER=1
      ;;
    --no-docker)
      DOCKER=0
      ;;
  esac
  shift
done

if [ "$CI" ]; then
  echo "==> Running as CI..."
  script/ci/server
elif [ "$DOCKER" -eq 1 ]; then
  echo "==> Running with Docker..."
  script/docker/server
else
  echo "==> Running natively (no docker)..."
  script/no-docker/server
fi
