#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally. Use variables to control how you want to provision
#                your local environment.

set -e

# Enable the running of this script from any subdirectory without moving to root
cd "$(dirname "$0")/.."

. script/all/process-script-args

if [ "$CI" ]; then
  echo "==> Running as CI..."
  script/ci/server
elif [ "$DOCKER" -eq 1 ]; then
  echo "==> Running with Docker..."
  script/docker/server
else
  echo "==> Running natively (no docker)..."
  script/no-docker/server
fi
