#!/bin/sh

# script/setup: Set up the application for the first time after cloning, or set
#               it back to the initial unused state.

set -e

# Enable the running of this script from any subdirectory without moving to root
cd "$(dirname "$0")/.."

echo "==> Loading command line options…"
DOCKER=${PREFER_DOCKER_FOR_DXW_RAILS:-0}
for arg in "$@"
do
  case $arg in
    --docker)
      DOCKER=1
      ;;
    --no-docker)
      DOCKER=0
      ;;
  esac
  shift
done

if [ ! -f .env.development.local ]; then
  echo "==> Copying default environment config..."
  cp .env.example .env.development.local
fi

if [ "$DOCKER" -eq 1 ]; then
  echo "==> Setting up with Docker..."
  script/docker/setup "$@"
else
  echo "==> Settting up natively (no docker)..."
  script/no-docker/setup "$@"
fi
