#!/bin/sh

# script/test: Run the test suite for the application.
#
#              Optionally pass in a path to an individual test file to run a
#              single test.
#
#              Use variables to control how you want to provision your local
#              environment.
#              Eg. `DOCKER=true script/console`
#              Or, add this as a global variable to your shell so it's set
#              automatically.

set -e

# Enable the running of this script from any subdirectory without moving to root
cd "$(dirname "$0")/.."

echo "==> Loading command line options…"
DOCKER=${PREFER_DOCKER_FOR_DXW_RAILS:-0}
for arg in "$@"
do
  case $arg in
    --docker)
      DOCKER=1
      ;;
    --no-docker)
      DOCKER=0
      ;;
  esac
  shift
done

if [ "$CI" ]; then
  echo "==> Running as CI..."
  script/ci/test "$@"
elif [ "$DOCKER" -eq 1 ]; then
  echo "==> Running with Docker..."
  script/docker/test "$@"
else
  echo "==> Running natively (no docker)..."
  script/no-docker/test "$@"
fi
