#!/bin/sh

# script/test: Run the test suite for the application.
#
#              Optionally pass in a path to an individual test file to run a
#              single test.
#
#              Use variables to control how you want to provision your local
#              environment.

set -e

# Enable the running of this script from any subdirectory without moving to root
cd "$(dirname "$0")/.."

. script/all/process-script-args

if [ "$CI" ]; then
  echo "==> Running as CI..."
  script/ci/test "$@"
elif [ "$DOCKER" -eq 1 ]; then
  echo "==> Running with Docker..."
  script/docker/test "$@"
else
  echo "==> Running natively (no docker)..."
  script/no-docker/test "$@"
fi
