#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

# Enable the running of this script from any subdirectory without moving to root
cd "$(dirname "$0")/.."

. script/all/process-script-args

if [ "$DOCKER" -eq 1 ]; then
  echo "==> Running with Docker..."
  script/docker/update "$@"
else
  echo "==> Running natively (no docker)..."
  script/no-docker/update "$@"
fi
