#!/bin/sh

# Run the test suite for the application. This is primarily designed to run on
# CI with a clean build context. To run locally first remove any generic image
# by running `docker rmi app:latest`

set -e

docker-compose -f docker-compose.ci.yml \
               -p app \
               run --rm test \
               script/all/test "$@"
